### ISSUE TITLE
Issue: Body in html

### ISSUE THREAD

**Issue by yunabeza** [FAE-SEG2900-Group-19/FAE-SEG2900-Group-19.github.io#5]
Hi Guys,
I think the bug stands here. If you remove the reference "id=body", the header bar goes back to normal. Hence, the body potion in css affects the location page  on header bar in the buggy way.
Sample example:
- remove the id="body" from <body id="body"> in location.html to <body> only

https://github.com/FAE-SEG2900-Group-19/FAE-SEG2900-Group-19.github.io/blob/64c0efc22c776d04c85ee25a7fbfa4f5c0e02f33/locations.html#L15
Cheers,

**Comment by pradyuv** [comment]
Does this affect the nav bar is any other pages?

**Comment by yunabeza** [comment]
Nope. it doesn't. Just location.html

**Comment by pradyuv** [comment]
Nice. Have you removed it already?

**Comment by connorlucid** [comment]
you were right, removing that fixed it
good job!
